### ISSUE TITLE
Lier un tier-dolibar à un utilisateur-wp ne marche pas

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnector#1]
Bonjour, 

---
# environnement

php7.2
wp 5.1.1 ; doliconnect 3.4.1 ; 
dolibarr 9.0.2 ; doliconnector 9.0.1 ; adhérent+ 9.0.1

---
# description du problème

Doliconnector est doté d'une fonction permettant de lier un tier-dolibarr à un utilisateur-wp existant ou de créer un utilisateur-wp et le lier au tier-dolibarr, mais celà ne marche pas.

---
# comment reproduire le problème

- Aller sur la fiche d'un ters-dolibarr 
- Cliquer sur pas d'utilisateur wp synchronisé (screenshot 1)
- Cliquer sur le bouton rouge créer et lier un utilisateur wordpress (screenshot 2)
- Valider le popup (pas de screenshot, mais avec un peu d'imagination c'est bon)
- une notification d'échec apparait en haut à droite (screenshot 3)

![image](https://user-images.githubusercontent.com/49561217/56043015-a50ca100-5d3c-11e9-9e11-e8dfa1dcbc92.png)

![Capture du 2019-04-12 16-01-25](https://user-images.githubusercontent.com/49561217/56043118-e7ce7900-5d3c-11e9-8fc2-c8f4512615f4.png)

![Capture du 2019-04-12 00-34-19](https://user-images.githubusercontent.com/49561217/56043208-1a787180-5d3d-11e9-8757-622f0852809c.png)

**Comment by ptibogxiv** [comment]
@Kwagga-Quagga testé  à l'instant. La lliste est celle des user wordpress sous réserve que l'utilisateur utilisé en ai le droit.

 la liaison avec utilisateur déjà existant fonctionne mais pas la création... investigation en cours.

**Comment by Kwagga-Quagga** [comment]
> @Kwagga-Quagga testé à l'instant. La lliste est celle des user wordpress sous réserve que l'utilisateur utilisé en ai le droit.

ici "lutilisateur utilisé" vous voulez dire,
1) l'utilisateur dolibar actuellement connecté ?  (c'est le SuperAdmin) 
2) l'utilisateur wp renseigné dans les pférérence de doliconnector (c'est aussi le SuperAdmin)
3) l'utilisateur wp qui aspire à être lié ? 

> 
> la liaison avec utilisateur déjà existant fonctionne mais pas la création... investigation en cours.

ok je n'ai pas encore pu tester pour les raisons ci dessus

**Comment by ptibogxiv** [comment]
oui l'utilisateur rensiegné dans doliconnector doit être admin.

 la liste affichés est la liste des utilisateurs du wordpress

**Comment by Kwagga-Quagga** [comment]
Ok, ça confirme mes hypothèses, et le problème

L'utilisateur renseigné dans doliconnector est bien admin de wordpress, pour autant la liste des utilisateur wp demeure vide.

Pour moi il est donc impossible 
- de lier un tiers-dolibar à utilisateur-wp existant, 
- de créer un utilisatuer-wp à partir d'un tiers-dolibarr

**Comment by ptibogxiv** [comment]
La liaison est automatique depuis le wordpress  si le mail utilisé existe déjà dans un tiers Dolibarr. Il n'y a donc pas de nécessité à les créer manuellement.... j'enquête toujours sur cette partie.

pour lier, il faut qu'il y ai des utilisateurs wordpress et que l'utilisateur admin puissent les voir dans l'entité en question.
-> les API REST wordpress sont -elle desactivées ? bcp de module de sécurité les bloquent...

**Comment by ptibogxiv** [comment]
@Kwagga-Quagga l'url du wordpress est pour le moment celle de la société déclaré dans la partie configuration: Société/Organisation (doliconnector ne peut deviner sinon l'url du site).

**Comment by Kwagga-Quagga** [comment]
> @Kwagga-Quagga l'url du wordpress est pour le moment celle de la société déclaré dans la partie configuration: Société/Organisation (doliconnector ne peut deviner sinon l'url du site).

ok, je m'était également demandé comment celà pouvait aller dans le sens dolibarr->wp sans champ url pour indiquer ou se trouve le site wp, mais je m'était dit que doliconnect poussait peut être l'info à doliconnector

**Comment by Kwagga-Quagga** [comment]
L'api wp est bien active, et je ne pense pas qu'elle soit bloquée car jl'url https://monsite.fr/wp-json/ me retoune un code http 200 et le fichier json s'affiche 
je n'ai auccun modules complètmentaire pour l'instant à part doliconnect et transciant mananger


Mais j'ai tout de même "que ça" 
![Capture du 2019-04-15 12-10-02](https://user-images.githubusercontent.com/49561217/56125426-2cdeef00-5f79-11e9-91ee-af7f76c09569.png)

**Comment by ptibogxiv** [comment]
il faut juste mettre l'ul ex: https://www.monsite.fr

**Comment by Kwagga-Quagga** [comment]
> il faut juste mettre l'ul ex: https://www.monsite.fr

oui bien entendu, dans dolibarr > configuration > société /organisation > web : j'ai bien saisi https://monsite.fr 

l'url https://monsite.fr/wp-json, n'est ici mentionné que pour confimer que l'api de wordpress fonctionne.


avant de renseigner l'url de mon site wordpress, la liste était complèutement vide, maintenant doliconnector voit 3 utilisateur-wp, mais ne ramène pas d'information les concernant

**Comment by ptibogxiv** [comment]
la synchro nécessite un email des 2 côtés car les requêtes se font là dessus (il faut que je mette des controles pour vérifier et nécessité cela)

**Comment by Kwagga-Quagga** [comment]
> la synchro nécessite un email des 2 côtés car les requêtes se font là dessus (il faut que je mette des controles pour vérifier et nécessité cela)

tout mes utilisateur wp on un email renseigné et de même pour mes utilisateur dolibarr


ps : au delà du fait que l'email est le champs qui va servir de dénominateur commun pour les compte utilisateur-wp et tiers-dolibarr, je ne comprends pas vraiment votre réponse

**Comment by ptibogxiv** [comment]
la synchro passe par les tiers ^^ le tiers utilisé n'a pas d'email.

**Comment by Kwagga-Quagga** [comment]
> la synchro passe par les tiers ^^ le tiers utilisé n'a pas d'email.

oui pardon, le screen shot est trompeur, car mes essais concerent d'autres tiers.

Mais en ajoutant un email à ce tiers, et créant manuellement un utilisateur wp avec le même email le problème persiste : 

j'ai trois lignes d''utilisateur dolibarr, mais rien dedans
![Capture du 2019-04-15 12-43-22](https://user-images.githubusercontent.com/49561217/56126893-4afa1e80-5f7c-11e9-90be-b9cf5e05b2fc.png)

**Comment by ptibogxiv** [comment]
dans le code de cette page, il faut decommenter la ligne 266 et voir ce que dolibarr recupère comme un info de wordpress...

**Comment by Kwagga-Quagga** [comment]
yes
sans grande surprise j'ai ça 
`{"code":"rest_forbidden_context","message":"D\u00e9sol\u00e9, vous n\u2019avez pas l\u2019autorisation de lister les utilisateurs.","data":{"status":401}}`

cependant l'utilisateur wordpress informé dans doliconnector est admin wp, et les id/pass sont vérifié par 3 fois (qui plus est sans caractères spéciaux ou autre)


en fouillant un peu je constate que 
https://monsitewordpress.fr/wp-json/wp/v2/users

ne me retourne qu'un utilisateur, dont l'id est 1 et qui est bien celui renseigné lors de la creation du site wp

**Comment by ptibogxiv** [comment]
@Kwagga-Quagga le problème est dans wordpress et pas lier a mes modules... qqch bloque l'affichage et l'utilisateur entière de l'API

**Comment by ptibogxiv** [comment]
@Kwagga-Quagga je vais réfléchir à ce qui peut bloquer... étrange... ça marche sur toutes mes installations

**Comment by Kwagga-Quagga** [comment]
> @Kwagga-Quagga le problème est dans wordpress et pas lier a mes modules... qqch bloque l'affichage et l'utilisateur entière de l'API

oui, ca vient de là, mais c'est pas facile à trouver quand une partie des problèmes est lié à des bug des modules doliconnect/or et d'autre à leurs configurations ou à l'environnement sur lesquels ils tournent


mais j'ai trouvé, problème wordpress classique : 

j'ai du ajouter `RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]` juste après `RewriteEngine On` dans le fichier .htaccess à la racine de wp... 
[voir ici](https://github.com/WP-API/Basic-Auth/issues/35)

par contre je ne suis pas sûr que ce soit une solution durable car apparement wp réécrit le fichier .htaccess de temps à autre... ???

**Comment by ptibogxiv** [comment]
non mais c'est la seule... les API restent  sont très dépendant de l'environnement... dont l'htaccess... oui wordpress ou certains modules de sécurité peuvent mais il ne toucheront pas ces lignes nécessaires au rewrite... C'est pb se rencontrent surtout sur les serveurs auto installé VPS... en mutualisé cela est optimisé par défaut...

**Comment by Kwagga-Quagga** [comment]
> non mais c'est la seule... 

 ? seule quoi , j'ai pas compris :-)

> les API restent sont très dépendant de l'environnement... dont l'htaccess... oui wordpress ou certains modules de sécurité peuvent mais il ne toucheront pas ces lignes nécessaires au rewrite... C'est pb se rencontrent surtout sur les serveurs auto installé VPS... en mutualisé cela est optimisé par défaut...

alors apparement le pb se pose souvent sur des serveur php-cgi d'une part et en mutualisé d'autre part car les header http d'autentification sont souvent tronqués par défaut par le serveur (j'ai lu ça je sais plus où en faisant me recherches).


autrement ça me parait plus propre d'ajouter ça au niveau du vhost 
`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>
`

Comme ça on vient pas bidouiller au niveau des fichiers générés par wordpress.

**Comment by ptibogxiv** [comment]
@Kwagga-Quagga l'active du mod_rewrite est nécessaire à wordpress pour de nombreux modules et fonctions dont l'usage des API REST. En mutualisé,ou sur certaines distributions, c'est en effet gérer nativement sans modification

**Comment by Kwagga-Quagga** [comment]
yes, mais mod rewrite ne suffit pas, il était déjà activé, mais sans la ligne `RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`ou si elle n'est pas au tout début du fichier .htaccess à la racine de wp ou au niveau du vhost, l'api n'est pas accessible depuis l'extérieur (enfin pour être précis il se peut que l'api ne soit pas accessible depuis l'extérieur) ;

**Comment by ptibogxiv** [comment]
Fixe ds la dernier version
