### ISSUE TITLE
Erreur après installation module custom doliconnector-10.0.0

### ISSUE THREAD

**Issue by hornopiren** [ptibogxiv/doliconnector#2]
Dolibarr (10.0.0) + WP (5.2.2) + doliconnect (3.7.2) + doliconnector (10.0.0) en dernières versions.

- Module dolibarr API/Web services (serveur REST) activé
- Clé API générée sur la fiche du user admin Dolibarr
- Plugin doliconnect installé puis activé et paramétré dans WP
- Module doliconnector installé puis activé dans Dolibarr

WP indique me dit "Il semble que votre version de Dolibarr et/ou ses plugins ne sont pas à jour!"
Dans Dolibarr quand je clique sur l'icône de paramétrage de doliconnector j'arrive sur une page 404

**Comment by hornopiren** [comment]
(merci pour le dev au fait)

**Comment by ptibogxiv** [comment]
Bonjour, le module doit être installer dans le directory custom et bien etre sous la forme htdocs/custom/doliconector/ "contenu du dossier et fichiers"

Pour la partie dolibarr, il faut s'assurer que l'url de votre wordpress soit bonne, en https et que les api REST / curl soit bien activé (il y a des pb avec certains hébergeurs qui n'ont pas une installation standard)

Merci pour votre retour.

**Comment by hornopiren** [comment]
J'ai renommé /custom/doliconector-10.0.0 en /custom/doliconector et je n'ai plus la page 404 quand j'accède aux réglages.
En revanche je ne vois pas où dans doliconnector configurer l'URL de mon WP.

**Comment by ptibogxiv** [comment]
bien vu! je vais le rajouter pour la 10.0.1 en attendant, il faut utiliser l'url dans les paramètres de votre société

**Comment by hornopiren** [comment]
Ce champ ? Je n'en vois pas d'autre.
![01-08-2019 19-03-58](https://user-images.githubusercontent.com/53576333/62312733-43a94300-b48f-11e9-8a0c-f9a3be7df581.jpg)

Et WP râle toujours : 
![01-08-2019 19-05-44](https://user-images.githubusercontent.com/53576333/62312805-6dfb0080-b48f-11e9-8b61-160f61d4f3d9.jpg)

**Comment by hornopiren** [comment]
Pour info ça n'est pas une fresh install dolibarr 10.0.0 mais un upgrade depuis la 9

**Comment by ptibogxiv** [comment]
pour le champ url en effet

pour wordpress, il rale car il n'arrive pas à se connecter efficacement. si lesparamètres sont bons,  cela doit indiqué statut 200 sur la page de paramètres

**Comment by hornopiren** [comment]
Pas mieux.
Dans la config doliconnector faut renseigner les champs DOLICONNECT_USER et DOLICONNECT_PASSWORd ?
J'ai essayé, mais sans succès non plus.

**Comment by ptibogxiv** [comment]
il faut mettre url du style https://www.votresite.fr

oui il faut mettre un identifiant et un mot de passe admin de wordpress pour que dolibarr puisse agir sur le wordpress

**Comment by PHPcli** [comment]
Bonjour @ptibogxiv 
Je me permets d'ajouter à ce fil, j'ai bien résolu le souci de redirection évoqué plus haut.
Je mets en place bénévolement pour une association un couple WP/Dolibarr qui répondrait à la demande.
La solution que tu as développée semble correspondre parfaitement à la problématique de liaison entre WP et DLB. 

J'ai installé les dernières versions de WP et de l'extension et la dernière version de Dolibarr et de l'extension DLB (10.0.3) sur un sous domaine ( gestion.monsite.com).
J'ai bien été jusqu'au post précédent, mais il me manque quelques éléments pour bien comprendre
Il y a des éléments demandé que je ne sais pas remplir
sur l'extension DLB les éléments RootCategoryForDolishop et DoliconnectIdWareHouse

Enfin sur l'extension WP sur l'onglet Key and setting DOLIBARR REST API USER KEY. J'imagine que je dois la génerer dans DLB, mais je n'ai pas trouvé où.
Enfin dans l'onglet doliconnect sur le WP, les éléments dolibarr_shop ... renvoient vers un menu déroulant de pages WP. Je n’ai pas trop compris le principe. 

Je trouve peu de documentation ou de tuto pour installer facilement ta solution qui a l'air vraiment chouette Thibault.

**Comment by ptibogxiv** [comment]
@PHPcli  merci pour ce retour

la clé DOLIBARR REST API USER KEY est à générer et retrouver après avoir activer le module API REST dans dolibarr sur la fiche d'un utilisateur Dolibarr (lui donner les bons droit ou le rendre admin) LEs ction générer dans wordpress passeront et seront traer comme venant de cet utilisateur

dans mon module , pas de  shortcode, tu crées des pages wordpress avec le nom de ton choix et le module et le module générera l'affichage du bon code sur ces pages.

Pour le tuto, c'est ds ma liste des choses à faire pour début 2020. Il y a peu de choses à régler dans wordpress, le module réagit au paramètres de dolibarr.

**Comment by PHPcli** [comment]
Autant je maitrise WP autant Dolibarr est une découverte.
Je vais me baser sur ce tuto
https://www.dolibarr.fr/forum/t/documentation-api-rest/25139
si cela te semble correcte.

Une fois que j'aurai dépatouiller cela je peut essayer de te filer un coup de main pour le tuto ;) (mais avant il faut que je comprenne ;) )

**Comment by ptibogxiv** [comment]
@PHPcli pour certains hébergeurs , il y a des soucis avec les PAI REST et dolibarr mais cela n'est pas propre à mon module qui utilise à 95% les API natives

oui ce tuto est correct ;)

**Comment by PHPcli** [comment]
On est sur serveur dédié. 
Token en place. 
![Capture d’écran 2020-01-20 à 14 13 36](https://user-images.githubusercontent.com/18071408/72729180-1496a300-3b8f-11ea-9bf6-aa697fa380c1.png)
Intégration des url et du token coté WP

![Capture d’écran 2020-01-20 à 14 48 04](https://user-images.githubusercontent.com/18071408/72731439-0a2ad800-3b94-11ea-9902-0b153ff965ec.png)

Création d'une page "dolibarr account" ajouté à la ligne "dolibarr_account"
![Capture d’écran 2020-01-20 à 14 15 40](https://user-images.githubusercontent.com/18071408/72729466-853dbf80-3b8f-11ea-98d3-3fe4688cd1e1.png)
Résultat

404 
![Capture d’écran 2020-01-20 à 14 17 28](https://user-images.githubusercontent.com/18071408/72729512-9b4b8000-3b8f-11ea-8482-f2131c514d62.png)

En indiquant l'adresse https://monsite.com/api/index.php, on retrouve bien un 404 renvoyé 
![Capture d’écran 2020-01-20 à 14 28 40](https://user-images.githubusercontent.com/18071408/72730313-6dffd180-3b91-11ea-91f5-59ced5d0bb63.png)

Il y a sans doute un truc qui m'a échappé 😣

**Comment by ptibogxiv** [comment]
@PHPcli Désolé de répondre que maintenant.. la derniere erreur semble être un pb de rewrite url au sein de wordpress, le module doliconnect vient simplement surcharger le contenu de la page indiqué par du contenu généré à l'aide des info de dolibarr.

**Comment by bf8392** [comment]
I have the same error I think...I translated the posts with google translator...I want to use your plugin, because i want a contact-form in wordpress...

**Comment by ptibogxiv** [comment]
Hi @bd8392 . For some serveur, Dolibarr need more configuration for REST API functionnality. It seems it's fixed with v11. 

Whats exactly your mistake ?

**Comment by bf8392** [comment]
I don't know what im doing wrong...I've tried the connector in verison 11.0.0 on dolibarr side, and 11.0.3...the rest api is active, and i used the rest-api code of the one and only admin-user...the rest-api explorer works fine...on the wordpress side, I inserted the link to wordpress and wp-login...

I always get:
```
It seems that your version of Dolibarr and/or its plugins are not up to date!
```

**Comment by bf8392** [comment]
My dolibarr version is 11.0.0. The connector is also 11.0.0

**Comment by ptibogxiv** [comment]
the mistake is your serveur, for some configuration, REST API is blocked

have you set correct API  with good rights ?

![image](https://user-images.githubusercontent.com/3135833/78458081-1ad8ed80-76af-11ea-864f-7075ed6d4bea.png)

check your transients (doliconnect save API Returns there) with this

https://wordpress.org/plugins/transients-manager/

**Comment by bf8392** [comment]
Do you have a guide how to setup api? because I just enabled it in the modules section...then i created the api code from the administrator (most extensive rights)...is this wrong?

**Comment by ptibogxiv** [comment]
It's right but the mistake probable comes from your hosting

**Comment by bf8392** [comment]
I host a root-server...

**Comment by bf8392** [comment]
Can it be a problem, that wordpress and dolibarr re behind a reverse-proxy? but it is modiefied to pass hosts-headers (traefik)

**Comment by ptibogxiv** [comment]
Nota bene, https is required 😏😉

**Comment by bf8392** [comment]
the proxy does the https in my case...I guess this is not sufficient?

**Comment by ptibogxiv** [comment]
> Can it be a problem, that wordpress and dolibarr re behind a reverse-proxy? but it is modiefied to pass hosts-headers (traefik)

yes it's possible, proxy can filter the response

**Comment by bf8392** [comment]
okay i will try to resolve...thanks!

**Comment by ptibogxiv** [comment]
> okay i will try to resolve...thanks!

read this, it could help you: 
https://github.com/Dolibarr/dolibarr/pull/12089

**Comment by bf8392** [comment]
Foun the issue! it is realted to iptables input chain was set to drop...do you know which rule i woluld need? regarding running wordpress and dolibarr in docker...

**Comment by ptibogxiv** [comment]
> Foun the issue! it is realted to iptables input chain was set to drop...do you know which rule i woluld need? regarding running wordpress and dolibarr in docker...

no i don't know the correct rules for you configuration. wordpress and dolibarr must see each other with external ip/domain not internal

**Comment by bf8392** [comment]
OHHH Okay =) Thanks =) I found the correct rule in case you need it =)
```
iptables -A INPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate ESTABLISHED -j ACCEPT

**Comment by bf8392** [comment]
Plugin perfectly connected =) Thanks for the fast support and Help =)

**Comment by bf8392** [comment]
Do you have a good tutorial, how to build an onlineshop with dolibarr and wordpress? =) Your plugin is the best and most updated I found =) Maybe I can help you with docs if you want =)

**Comment by bf8392** [comment]
I get satus 200 now but this message still appears: 
```
It seems that your version of Dolibarr and/or its plugins are not up to date!
```
I use monogramm/dolibarr, which is not always the latest version...(11.0.0 instead of 11.0.3). is there a posibility to supress this message? or does it just say I don't use the latest oliconnector? because I use 11.0.0 there also...

**Comment by ptibogxiv** [comment]
> I get satus 200 now but this message still appears:
> 
> ```
> It seems that your version of Dolibarr and/or its plugins are not up to date!
> ```
> 
> I use monogramm/dolibarr, which is not always the latest version...(11.0.0 instead of 11.0.3). is there a posibility to supress this message? or does it just say I don't use the latest doliconnector? because I use 11.0.0 there also...

message is for remind to update.... severals important fix are released in 11.0.3 (or upgrade in new dolibarr branche with new usefull API

**Comment by bf8392** [comment]
okay thank you =)

**Comment by ptibogxiv** [comment]
> Do you have a good tutorial, how to build an onlineshop with dolibarr and wordpress? =) Your plugin is the best and most updated I found =) Maybe I can help you with docs if you want =)

you can use functions of the plugin and build your own (or enhance woocommerce with), but you can use internal doliconnect online shop too. 

This shop is basic for the moment but functionnal (with some ajax script). feel free to contribute ;)  (and without external  sync server as splashsync)

**Comment by bf8392** [comment]
Very cool! Thanks for all the development ad opensourcing this! You are a dolibarr Hero! =)

**Comment by ptibogxiv** [comment]
> Very cool! Thanks for all the development ad opensourcing this! You are a dolibarr Hero! =)

not hero but top 10 developer ;) (and wordpress dev in progress)

**Comment by bf8392** [comment]
I've found one problem...I want to limit the dolibarr api acces to ip adress...but the wordpress docker seems to request with docker_gwbridge ip instead of real ip...is there a possibility to get around this?

**Comment by bf8392** [comment]
(i'm running in swarm)

**Comment by ptibogxiv** [comment]
> I've found one problem...I want to limit the dolibarr api acces to ip adress...but the wordpress docker seems to request with docker_gwbridge ip instead of real ip...is there a possibility to get around this?

Never try this config 🤨 but you can lock rest api internally within dolibarr settings for some ip

Here I can do only support for doliconnect not full dolibarr and WordPress 😅

**Comment by bf8392** [comment]
yes the rest-api internal setting was the one i meant =) This setting is only working with the ip-adress of docker_gwbridge not real ip...it seams that the header in the request of the api takes the ip from the docker_gwbridge? No problem =) Maybe someone else finds a solution ;-)
