### ISSUE TITLE
not connecting

### ISSUE THREAD

**Issue by KarryonDesigns** [ptibogxiv/doliconnector#3]
I have the plugins installed on both wordpress and dolibarr.  I have the wordpress config set up to the dolibarr address (domain.com/crm) which is where dolibarr is installed.  Then I have the website set up in my company information in dolibar set to domain.com/wp-login.  I have an admin user created on both wordpress and dolibar and have the api key added to doliconnect in wordpress and the wordpress username and password added in the dolibar config.  nothing is working.  Any ideas?

**Comment by ptibogxiv** [comment]
What do you mean with nothing is working ???

**Comment by KarryonDesigns** [comment]
On the wordpress side its showing that dolibar is offline, its hosted on
the same domain just in another directory. I've checked the addresses and
added the users and nothing is syncing

**Comment by ptibogxiv** [comment]
Your serveur could have curl api rest not activated or Cdn/security plugin blocked. 

By default it's not safe to have WordPress and dolibarr in same directory. It's better with less interference to have www/wordpress and  www/dolibarr with différent subdomain. WordPress or a plugin can interact with api of dolibarr and block it.

**Comment by KarryonDesigns** [comment]
I'll have to upgrade my ssl to move dolibar which I can do this weekend.  Both api's are open from what I can tell but they aren't communicating Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: ptibogxiv <notifications@github.com> Date: 8/2/19  3:58 PM  (GMT-07:00) To: ptibogxiv/doliconnector <doliconnector@noreply.github.com> Cc: KarryonDesigns <karryondesigns@gmail.com>, Author <author@noreply.github.com> Subject: Re: [ptibogxiv/doliconnector] not connecting (#3) Your serveur could have curl api rest not activated or Cdn/security plugin blocked.

By default it's not safe to have WordPress and dolibarr in sale directory. It's better with less interference to have www/wordpress and  www/dolibarr with différent subdomain. WordPress can interact with api of dolibarr and block it.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ptibogxiv/doliconnector/issues/3?email_source=notifications\u0026email_token=ABMTIYRLWLMJKAX4KRVSD7LQCS33HA5CNFSM4IJAFC72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3PAKYA#issuecomment-517866848",

"url": "https://github.com/ptibogxiv/doliconnector/issues/3?email_source=notifications\u0026email_token=ABMTIYRLWLMJKAX4KRVSD7LQCS33HA5CNFSM4IJAFC72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3PAKYA#issuecomment-517866848",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ptibogxiv** [comment]
check you server / hosting settings. principal mistakes is curl not activate or block by serveur or some security code. 

have you test your domain.com/crm/api/index.php/explorer ? can you see and test api ?for more confidential test you can mail me to: support at ptibogxiv.net

**Comment by KarryonDesigns** [comment]
Yea I have checked that and it works fine
 I had to make an adjustment to the code to make it work but its apparently
a common issue with linux hosting
