### ISSUE TITLE
Failed to load module descriptor class for Doliconnector

### ISSUE THREAD

**Issue by PhilEngel** [ptibogxiv/doliconnector#4]
copied zip to custom folder and extracted shows in modules in Version Dolibarr 10.0.1 but get Failed to load module descriptor class for Doliconnector.

**Comment by ptibogxiv** [comment]
As other posts or issues hzre, install à tu should be

Htdocs/custom/doliconnector/"files of doliconnector"

**Comment by PhilEngel** [comment]
yes it is htdocs/custom but the zip file after decompress is dolibarr 10.0.0, I did remove the 10.0.0 and now the error message is gone, however I now get "That page can’t be found." when selecting setup

**Comment by ptibogxiv** [comment]
Url admin page is htdocs/custom/doliconnector/admin/doliconnector.php

If you can't get it, your installation is bad.

**Comment by PhilEngel** [comment]
that file exists where you say it must but page do not open, "page cannot be found" error

**Comment by ptibogxiv** [comment]
Check the link/page of the url. If file existe and url good, it's impossible to have page cannot be found.

**Comment by PhilEngel** [comment]
ok, file and folder permissions seem to have been to problem, folders to 755 and file to 644, will update further..

**Comment by PhilEngel** [comment]
everything is setup, how do I synchronize contacts?

**Comment by ptibogxiv** [comment]
doliconnector don't sync!

doliconnect link a wordpress user to a thirdparty with none or several contacts as alternative address
doliconnect auto recognize thirdparty from an wordpress's user from the email address and so link it.

**Comment by PhilEngel** [comment]
or users or customers, can any of these be synchronized?

**Comment by PhilEngel** [comment]
your description is: Sync Dolibarr with Wordpress via Doliconnect

**Comment by ptibogxiv** [comment]
we only sync as push/pull infos/objects but not mass sync, so heavy for lot of installation. 

instead of sync, we auto link from email address (avoid sync old thirdparty who never connect to wordpress.
