### ISSUE TITLE
No adhesion showed on Wordpress but lots in Dolibarr

### ISSUE THREAD

**Issue by daraelmin** [ptibogxiv/doliconnector#5]
# Environnement
Wordpresse  5.1.5 
Dolibarr 11.0.3
Doliconnector 11.0.3
Adherentplus 11.0.3
Doliconnect compatbile

# Context
Notre association vient de passer à Dolibarr. Dans un premier temps, nous avons juste importé la base de donnée des membres et l'historique de leur cotisation. 

Nous n'utilisions pas jusqu'ici le module Tiers. Il vient d'être installé et les tiers-adhérents ont été créer depuis le menu adherent.

Nous n'utilisons toujours pas le module de comptabilisation, ni le module de paiement en ligne car avant de le faire nous voulons déjà tester la comptabilité avec le site vitrine.

Tout s'est bien déroulé pour linstallation. J'ai mis un peu de temps à comprendre qu'il faut recréer les utilisateurs wordpress pour que le lien se fasse (pas de synchro au départ).

# Bug
Bref, maintenant que le lien entre user WP et user DB est fait, il apparaît que les informations affichées sont celles, lacunaires, du tiers (créer pour l'occasion depuis adherentplus), et qu'on ne peut pas voir d'historique de cotisation. 

Pire, l'adhésion n'est pas prise en compte pour la période courante.
Que manque-t-il pour que le lien se fasse ?

**Comment by ptibogxiv** [comment]
Pour que tout fonctionne pour votre usage il faut des éléments de la version pro qui vont arriver dans la version gratuite en mai. Il faut aussi que vous ayez bien renseigné les types et mis un produit/service qui sera utiliser pour les adhesions. 

Il faut en effet utiliser les tiers, pour ainsi passer des commandes qui seront facturable et générer ont une adhésion.

**Comment by daraelmin** [comment]
Voilà ce que j'ai saisi de votre réponse
1) La synchronisation des user WordPress depuis Dolibarr se fera prochainement dans la version gratuite, mais est disponible actuellement dans une version pro. Je n'ai pas trouvé le lien pour acheter la licence.

2) Les adhésions en cours (celle qui ont été importées) seront "actif" dès que nous aurons crée un service, recréé des factures et les paiements liés ? Cela me semble un peu lourd... pour les 600 adhésions en cours de validité. Est-ce possible de faire cela avec un import csv ?

3) Les types d'adhésions/cotisations sont définies avec un prix dans adherentplus, mais je soupçonne que ce n'est pas de cela que vous parliez. Quel type dois-je définir, le service, le tiers ?

4) Nous aurions dû importer nos adhérents dans les tiers pour que les informations soient gérées complétement depuis WordPress. J'imagine que c'est toujours faisable. Il suffit de faire un import similaire à celui des adhérents et de lier ces deux parties. j'avoue que, du coup, je ne saisi pas bien l'utilité d'avoir ses informations répliquées dans la même bdd. Pour la suite, est-ce que les modifications du Tiers impacterons l'enregistrement dans la table adherent ?

Merci de la rapidité de votre réponse et de tout votre travail sur ces projets.

**Comment by ptibogxiv** [comment]
1/ non meme avec PRO il n'y a aucune synchro automatique,  cela pose trop de problèmes... mais si un email de tiers est utiliser le lien se fait automatiquement entre utilisateur wordpress et tiers (l'element de lien etant l'adresse email qui doit être unique pour chaque tiers)

2/ pour ce point vous devez avoir problème de paramétrage, usage de dolibarr, compliqué de vous répondre sans voir ni accéder a votre dolibarr. Vous êtes un grand compte/asso. il est possible que vous deviez réencoder /compléter des éléments mais là encore sans voir...

3/vous devez dans le module adhérents/adhérentsplus dans les paramètres définir un produit/service qui sera utiliser dans les commandes factures pour les adhésions.

4/ les modifications adhérents/tiers se répercutent les uns sur les autres mais là encore votre cas dépasse celui d'une petite asso. Pour un grand compte/asso comme la votre un support.

L'utilité c'est que l'element central dans dolibarr et le tiers, les adhérents c'est comme les contacts ou d'autres choses un addon mais tout le reste est basé sur le tiers.

**Comment by daraelmin** [comment]
Bonjour,

Nous sommes intéressé par un support, idéalement le vôtre. 

Nous vous avons envoyé un mail début août à ce sujet, via le formulaire de contact de votre site pour convenir d'un entretien téléphonique, mais nous n'avons pas reçu de réponse à ce jour.  

Cordialement.

**Comment by ptibogxiv** [comment]
Bonjour,

Je n'ai pas reçu de message a priori et encore moins non répondu. Vous pouvez me contacter en direct à support@ptibogxiv.net

**Comment by ptibogxiv** [comment]
je viens de répondre à votre email.
