### ISSUE TITLE
Affichage triple

### ISSUE THREAD

**Issue by esteban-digitaldilemma-fr** [ptibogxiv/doliconnector#7]
Wordpress 6.0.2
Dolibarr 16.0.0
Problème d'affichage depui update en dolibarr 16

![image](https://user-images.githubusercontent.com/91173421/192003065-473c59bb-ddd2-470f-88c8-a22e8050615a.png)

**Comment by ptibogxiv** [comment]
bon c'est étrange car je n''est rien changer qui pourrait expliquer cela. avez vous un ache ou eu une mise à jour du theme ?

**Comment by esteban-digitaldilemma-fr** [comment]
Le thème a été changé effectivement. Thème Zeever. Je vais regarder au niveau du thème si il 'y a pas des paramétrages possible
