### ISSUE TITLE
Impossible de connecter doli et wordpress

### ISSUE THREAD

**Issue by gti8sm** [ptibogxiv/doliconnector#8]
Bonjour,

Tout d'abord un énorme merci de nous faciliter la tache en interconnectant ses deux produits  et en faisant profiter tout le monde !!!

Mais, il y a un mais...
Je n'arrive pas a configurer la synchronisation 👍 
- hébergeur --> o2switch
- Doliconnector installé sur dolibarr vers 7.8.5
url wordpress entrée sur la conf de société
**par contre quand je vais sur les modules et que je clique sur la roue dentée, erreur url...**
J'ai copié les fichiers du module dans custom et je l'ai activé sur le listing des modules
- Doliconnect installé sur wordpress vers 18.0.3
Récup de l'adresse du site qui pointe sur l'api
Récupération du token
mais message
`Il semble que votre version de Dolibarr et/ou de ses plugins ne soit pas à jour !`

J'ai beau creuser je ne vois pas bien, meme si deux options sont plausibles 👍 
- problème sur le modules doli
- ou souci avec mon hébergeur.....

Merci pour votre aide, j'essaie de mettre en place un echange d'informations pour une asso :)

Bonne journée
Simon

**Comment by Matcinta** [comment]
Bonjour,
idem pour moi ce jour. Comment régler le problème ?
![image](https://github.com/ptibogxiv/doliconnector/assets/51161876/25b839b4-6afd-4316-b6d0-ec0773ca07d7)

Quand j'importe le zip de la 18.0.3, l'import est KO
![image](https://github.com/ptibogxiv/doliconnector/assets/51161876/0daf79dd-df2e-4bce-8ae7-7133251d9634)

Merci d'avance!
Mathilde

**Comment by ptibogxiv** [comment]
dolibarr et ses APi ne sont pas compatibles avec O2Switch sans modification du code cf forum dolibarr

sinon pour le reste il suffit de purger les transient au sein de votre wordpress pour normalement faire disparaitre le message.
